SSH_HOST=217.114.8.5
SSH_USER=root
DOMAIN=wclock5.startupassist.ru

REMOTE_PATH=/var/www/wclock5.startupassist.ru
NGINX_CONFIG_PATH=/etc/nginx/sites-available
INDEX_FILE=index.html

SSL_EMAIL=admin@startupassist.ru

PORT=10405

DOCKER_PREFIX=wclock5
